---

# 1.0 BASE
# =============================================================================
# 1.1 PHP
- import_playbook: playbooks/php.yml
# 1.2 Apache2
- import_playbook: playbooks/server.yml
# 1.3 SSL Certificates
- import_playbook: playbooks/ssl.yml
# 1.4 MySQL
- import_playbook: playbooks/mysql.yml
