- hosts: all
  become: yes

  tasks:
  
  - name: Install common packages
    apt:
      state: latest
      update_cache: yes
      pkg:
        - curl
        - git
        - jq
        - libsqlite3-dev
        - net-tools
        - software-properties-common
        - ruby-full
        - python3-pip

  # Install pyOpenSSL python library
  - name: Install pyOpenSSL
    shell: pip3 install pyOpenSSL
