- hosts: all
  become: yes
  vars:
    hostname: dev.wordpress
    php_ini:
      date.timezone: UTC
      default_charset: UTF-8
      mbstring.language: neutral
      mbstring.internal_encoding: UTF-8
      post_max_size: 1024M # Same with VVV
      short_open_tag: Off
      session.save_path: /tmp
      upload_max_filesize: 1024M # Same with VVV
      xdebug.remote_enable: true
      xdebug.remote_host: 127.0.0.1
      xdebug.remote_port: 9000
      xdebug.profiler_enable: true
      xdebug.idekey: VCCWDEBUG
      xdebug.remote_connect_back: true
      xdebug.remote_autostart: true

  tasks:
  
  # INSTALL MAILCATCHER AS ROOT
  - name: Install mailcatcher
    become: yes
    gem:
      name: mailcatcher
      state: latest
      user_install: no
  - name: Add mailcatcher to service
    become: yes
    template:
      src: templates/mailcatcher.service
      dest: /etc/systemd/system/mailcatcher.service
      mode: 0644
  - name: Start mailcatcher
    become: yes
    service: name=mailcatcher enabled=yes state=started
  - name: Update php.ini for mailcatcher
    become: yes
    lineinfile:
      dest: /etc/php/7.4/apache2/conf.d/99-vccw.ini
      create: yes
      line: "sendmail_path = /usr/bin/env catchmail"
    notify:
      - restart apache
  - name: Update php.ini for mailcatcher for cli
    become: yes
    lineinfile:
      dest: /etc/php/7.4/cli/conf.d/99-vccw.ini
      create: yes
      line: "sendmail_path = /usr/bin/env catchmail"

  handlers:
    - name: restart apache
      become: yes
      service:
        name: apache2
        state: restarted

        