- hosts: all
  become: yes
  vars:
    hostname: dev.wordpress
    document_root: /var/www/html

  tasks:
  # APACHE2
  - name: Install apache2 server
    apt:
      state: latest
      update_cache: yes
      pkg:
        - apache2
        - php7.4-fpm

  # APACHE2 MODULES
  - name: Activate module rewrite (apache2)
    apache2_module:
      state: present
      name: rewrite
  - name: Activate module ssl (apache2)
    apache2_module:
      state: present
      name: ssl
  # Flynt requirements
  - name: Activate module expires (apache2)
    apache2_module:
      state: present
      name: expires
  - name: Activate module headers (apache2)
    apache2_module:
      state: present
      name: headers
  - name: Activate module mime (apache2)
    apache2_module:
      state: present
      name: mime
  - name: Activate module env (apache2)
    apache2_module:
      state: present
      name: env
  - name: Activate module filter (apache2)
    apache2_module:
      state: present
      name: filter
  - name: Activate module deflate (apache2)
    apache2_module:
      state: present
      name: deflate
  - name: Activate module alias (apache2)
    apache2_module:
      state: present
      name: alias
  - name: Activate module actions (apache2)
    apache2_module:
      state: present
      name: actions
  - name: Activate module auth_basic (apache2)
    apache2_module:
      state: present
      name: auth_basic
  - name: Activate module proxy (apache2)
    apache2_module:
      state: present
      name: proxy
  # Flynt requirements ./end

  # HTTP2 requirements
  - name: Deactivate module php7.4 (apache2)
    apache2_module:
      state: absent
      name: php7.4
  - name: Deactivate module mpm_prefork (apache2)
    command: a2dismod mpm_prefork
    become: yes
  - name: Activate module mpm_event (apache2)
    command: a2enmod mpm_event
  - name: Activate module proxy_fcgi (apache2)
    apache2_module:
      state: present
      name: proxy_fcgi
  - name: Activate module setenvif (apache2)
    apache2_module:
      state: present
      name: setenvif
    become: yes
  - name: Activate module php7.4-fpm (apache2)
    shell: a2enconf php7.4-fpm
    become: yes
  - name: Start PHP7.4-FPM
    command: systemctl start php7.4-fpm
    become: yes
  - name: Add to startup PHP7.4-FPM
    command: systemctl enable php7.4-fpm
    become: yes
  - name: Enable PHP7.4-FPM as apache handler
    command: a2enconf php7.4-fpm
    become: yes
  - name: activate module HTTP2 (apache2)
    apache2_module:
      state: present
      name: http2
  # HTTP2 requirements ./end

  # START APACHE2
  - name: Make sure apache is running
    service:
      name: apache2
      state: started
      enabled: true

  # RELOAD APACHE2
  - name: Reload apache configuration
    command: systemctl restart apache2
    become: yes

  handlers:
    - name: restart apache
      action: service name=apache2 state=restarted
    - name: restart mysql
      action: service name=mysql state=restarted
