- hosts: all
  become: yes
  vars:
    settings.hostname: dev.wordpress
    document_root: /var/www/html

  tasks:

  # SSL CERTIFICATES
  - name: Create SSL dir
    become: yes
    file:
      path: /etc/apache2/ssl
      state: directory

  # Check if the keys have already been created and save result in 'key'
  # variable
  - name: Check if the key file already exists
    stat:
      path: /etc/apache2/ssl/{{ settings.hostname }}.key
    register: key

  # Creates a private key
  - name: Create key
    become: yes
    command: openssl genpkey \
     -algorithm RSA \
     -pkeyopt rsa_keygen_bits:2048 \
     -pkeyopt rsa_keygen_pubexp:65537 \
     -out /etc/apache2/ssl/{{ settings.hostname }}.key
    when: not key.stat.exists

  # Create Certificate Sign request
  - name: Generate an OpenSSL Certificate Signing Request with Subject information
    become: yes
    shell: openssl req -new \
     -key /etc/apache2/ssl/{{ settings.hostname }}.key \
     -out /etc/apache2/ssl/{{ settings.hostname }}.csr \
     -days 36500 \
     -subj "/C=DE/ST=Berlin/L=Berlin/O=coderman/OU=IT/CN={{ settings.hostname }}/emailAddress=admin@coderman.codes"
    when: not key.stat.exists

  # Setup CA certificate
  - name: Setup CA certificate
    become: yes
    template:
      src: templates/cacert.pem
      dest: /home/vagrant/cacert.pem
      mode: 0775
    when: not key.stat.exists

  # Setup CA key
  - name: Setup CA key
    become: yes
    template:
      src: templates/cakey.pem
      dest: /home/vagrant/cakey.pem
      mode: 0775
    when: not key.stat.exists

  # Setup environment for CA
  - name: Create config for CA
    template:
      src: templates/openssl.cnf
      dest: /home/vagrant/openssl.cnf
      mode: 0775
    when: not key.stat.exists

  # Create folders fo the CA
  - name: Create CA folders
    file:
      path: "{{ item }}"
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0775
    loop:
      - /home/vagrant/certs
      - /home/vagrant/crl
      - /home/vagrant/newcerts
      - /home/vagrant/private
    when: not key.stat.exists

  - name: Create CA files
    file:
      path: /home/vagrant/index.txt
      state: touch
      mode: u=rw,g=r,o=r
    when: not key.stat.exists

  - name: Write to serial file
    become: yes
    template:
      src: templates/serial
      dest: /home/vagrant/serial
      mode: 0775
    when: not key.stat.exists

  # Sign the certificates using the self CA
  - name: Sign the server certificates
    become: yes
    command: openssl ca -batch -updatedb \
      -days 36500 \
      -config /home/vagrant/openssl.cnf \
      -cert /home/vagrant/cacert.pem \
      -keyfile /home/vagrant/cakey.pem \
      -in /etc/apache2/ssl/{{ settings.hostname }}.csr \
      -out /etc/apache2/ssl/{{ settings.hostname }}.crt
    when: not key.stat.exists

  # Configure mutex for apache
  - name: Create mutex config file (apache)
    become: yes
    template:
      src: templates/mutex-file.conf
      dest: /etc/apache2/conf-available/mutex-file.conf
    when: not key.stat.exists

  - name: Enable mutex configuration
    become: yes
    shell: a2enconf mutex-file.conf
    when: not key.stat.exists

  # SETUP DEFAULT SITE CONFIG
  - name: Place /etc/apache2/sites-available/site.conf
    become: yes
    template:
      src: templates/site.conf
      dest: /etc/apache2/sites-available/000-default.conf

  # RELOAD APACHE2
  - name: Reload apache configuration
    command: systemctl restart apache2
    become: yes

  # RESTART APACHE2
  - name: Reload apache configuration
    service:
      name: apache2
      state: restarted
      
  handlers:
    - name: restart apache
      action: service name=apache2 state=restarted
    - name: restart mysql
      action: service name=mysql state=restarted
